import { registerBaselineSouls } from './baseline-souls';
import { registerBellEmpress } from './bell-empress';
import { registerCloudMirror } from './cloud-mirror';
import { registerKidomaru } from './kidomaru';
import { registerHearingSeaGoldfish } from './hearing-sea-goldfish';
import { registerEngagementGod } from './engagement-god';
import { registerMoonChaser } from './moon-chaser';
import { registerRedMaple } from './red-maple';
import { ContentRegistry } from './registry';
import { registerSkullGeneral } from './skull-general';
import { registerSongstress } from './songstress';
import { registerTrueFox } from './true-fox';
import { registerZashiki } from './zashiki';
import { registerLanternGhost } from './lantern-ghost';
import { registerSoulReaper } from './soul-reaper';
import { passiveSuppressionStatusDefinition } from '../core/passive-eligibility';
import { soulSuppressionStatusDefinition } from '../core/soul-eligibility';
import { registerFortuneCat } from './fortune-cat';
import { registerYinMoruo } from './yin-moruo';
import { registerNirvanaFire } from './nirvana-fire';
import { registerSoulBird } from './soul-bird';
import { registerWoodCharm } from './wood-charm';
import { registerReturnIncense } from './return-incense';
import { registerBellSpirit } from './bell-spirit';
import { registerSnowSpirit } from './snow-spirit';
import { registerDreamPillow } from './dream-pillow';
import { registerBatWing } from './bat-wing';
import { registerClothOfProtection } from './cloth-of-protection';
import { registerTreeSpirit } from './tree-spirit';
import { registerDamageScalingSouls } from './damage-scaling-souls';
import { registerDawnlessDusk } from './dawnless-dusk';
import { registerGravekeeperBeast } from './gravekeeper-beast';
import { registerPearl } from './pearl';
import { registerSoulDiver } from './soul-diver';
import { registerTulfo } from './tulfo';
import { registerTubingFire } from './tubing-fire';
import { registerRoundabout } from './roundabout';
import { registerFireCart } from './fire-cart';
import { registerDiekou } from './die-kou';
import { registerQingnufang } from './qingnufang';
import { registerYuanxingTemple } from './yuanxing-temple';
import { registerDustMound } from './dust-mound';
import { registerRampingSouls } from './ramping-souls';
import { registerControlSouls } from './control-souls';
import { registerReflectiveSouls } from './reflective-souls';
import { registerDebuffSouls } from './debuff-souls';
import { registerZhen } from './zhen';
import { registerRabbitMaru } from './rabbit-maru';
import { registerPeachBlossom } from './peach-blossom';
import { registerSnowGirl } from './snow-girl';
import { registerThreeTailFox } from './three-tail-fox';
import { registerCarpSpirit } from './carp-spirit';
import { registerKappa } from './kappa';
import { registerNineLivedCat } from './nine-lived-cat';
import { registerBoySoulSacrifice } from './boy-soul-sacrifice';
import { registerLittleGirl } from './little-girl';
import { registerEater } from './eater';
import { registerMengPo } from './meng-po';
import { registerWuguShi } from './wugu-shi';
import { registerGreatTengu } from './great-tengu';
import { registerYatagarasu } from './yatagarasu';
import { registerShutenDoji } from './shuten-doji';
import { registerFoodHairDemon } from './food-hair-demon';
import { registerSamuraiSpirit } from './samurai-spirit';
import { registerBoneGirl } from './bone-girl';
import { registerRainWoman } from './rain-woman';
import { registerJumpingBrother } from './jumping-brother';
import { registerJumpingYoungerBrother } from './jumping-younger-brother';
import { registerJumpingSister } from './jumping-sister';
import { registerBingyong } from './bingyong';
import { registerUglyWoman } from './ugly-woman';
import { registerOneEyedMonk } from './one-eyed-monk';
import { registerIronRat } from './iron-rat';
import { registerJiaoTu } from './jiao-tu';
import { registerGuanHu } from './guan-hu';
import { registerYamausagi } from './yamausagi';
import { registerFirefly } from './firefly';
import { registerButterflySpirit } from './butterfly-spirit';
import { registerTanuki } from './tanuki';
import { registerSeaMonk } from './sea-monk';
import { registerInsectMaster } from './insect-master';
import { registerLuminousMoonChaser } from './luminous-moon-chaser';
import { registerShuraKidomaru } from './shura-kidomaru';
import { registerJinkougyou } from './jinkougyou';
import { registerSeaMoonFireJade } from './sea-moon-fire-jade';
import { registerShikagamiCity } from './shikagami-city';
import { registerResentmentHannya } from './resentment-hannya';
import { registerCicadaSnowMaiden } from './cicada-snow-maiden';
import { registerChihime } from './chihime';
import { registerTanjiro } from './tanjiro';
import { registerNezuko } from './nezuko';
import { registerEmperorOfHeaven } from './emperor-of-heaven';
import { registerJi } from './ji';
import { registerTenjukka } from './tenjukka';
import { registerInuyasha } from './inuyasha';
import { registerWhaleSummoner } from './whale-summoner';
import { registerOmikane } from './omikane';
import { registerWisdomLamp } from './wisdom-lamp';
import { registerWorldLantern } from './world-lantern';
import { registerShiranui } from './shiranui';
import { registerFirstHaneMountainWind } from './first-hane-mountain-wind';
import { registerGhostServantWhite } from './ghost-servant-white';
import { registerHuaniaoJuan } from './huaniao-juan';
import { registerHuiyeji } from './huiyeji';
import { registerYanyanluo } from './yanyanluo';
import { registerJinyuhime } from './jinyuhime';
import { registerHuang } from './huang';
import { registerShinkiHuang } from './shinki-huang';
import { registerYijinzhentian } from './yijinzhentian';
import { registerXiazhongshaonv } from './xiazhongshaonv';
import { registerBiganhua } from './biganhua';
import { registerXiaosongwan } from './xiaosongwan';
import { registerShuweng } from './shuweng';
import { registerMountainChild } from './mountain-child';
import { registerInuGod } from './inu-god';
import { registerPuppetMaster } from './puppet-master';
import { registerShoumu } from './shoumu';
import { registerLanternBoy } from './lantern-boy';
import { registerBeichuifang } from './beichuifang';
import { registerWorldConch } from './world-conch';
import { registerEvilFloor } from './evil-floor';
import { registerNightSendDog } from './night-send-dog';
import { registerNightTearStone } from './night-tear-stone';
import { registerRainfallStone } from './rainfall-stone';
import { registerRemembranceFire } from './remembrance-fire';
import { registerOilChild } from './oil-child';
import { registerOceanAtlas } from './ocean-atlas';
import { registerJue } from './jue';
import { registerRedTongue } from './red-tongue';
import { registerFrogPorcelain } from './frog-porcelain';
import { registerJudge } from './judge';
import { registerPhoenixFire } from './phoenix-fire';
import { registerVampirePrincess } from './vampire-princess';
import { registerDemonFox } from './demon-fox';
import { registerEnma } from './enma';
import { registerYaoqinShi } from './yaoqin-shi';
import { registerDreamEater } from './dream-eater';
import { registerTwoFacedBuddha } from './two-faced-buddha';
import { registerYoungDeer } from './youngdeer';
import { registerKiyohime } from './kiyohime';
import { registerKamaitachi } from './kamaitachi';
import { registerUbume } from './ubume';
import { registerTwoMouthGirl } from './two-mouth-girl';
import { registerLanternSpirit } from './lantern-spirit';
import { registerWhiteWolf } from './white-wolf';
import { registerSakuraFairy } from './sakura-fairy';
import { registerIbarakiDoji } from './ibaraki-doji';
import { registerEbisu } from './ebisu';
import { registerHannya } from './hannya';
import { registerEchoingInsect } from './echoing-insect';
import { registerFlyingEdge } from './flying-edge';
import { registerGenericFallbackHeroes } from './generic-fallback';
import { registerArakawa } from './arakawa';
import { registerYaodaoJi } from './yaodao-ji';
import { registerLuoxinfufu } from './luoxinfufu';
import { registerYiMuLian } from './yimulian';
import { registerQingfangzhu } from './qingfangzhu';
import { registerGulonghuo } from './gulonghuo';
import { registerWannianzhu } from './wannianzhu';
import { registerYasha } from './yasha';
import { registerHeitongzi } from './heitongzi';
import { registerBaitongzi } from './baitongzi';
import { registerXuetongzi } from './xuetongzi';
import { registerBaimugui } from './baimugui';
import { registerNuraRiku } from './nura-riku';
import { registerMountainWind } from './mountain-wind';
import { registerRihefang } from './rihowan';
import { registerTamamo } from './tamamo';
import { registerXun } from './xun';
import { registerJuzu } from './juzu';
import { registerXiaoxiu } from './xiaoxiu';
import { registerYi } from './yi';
import { registerMaiyaolang } from './maiyaolang';
import { registerCatManager } from './cat-manager';
import { registerGuideng } from './guideng';
import { registerAxiang } from './axiang';
import { registerPeachMaki } from './peach-maki';
import { registerMenreiki } from './menreiki';
import { registerOnikiri } from './onikiri';
import { registerSesshomaru } from './sesshomaru';
import { registerYouthfulOotengu } from './youthful-ootengu';
import { registerWhiteFox } from './white-fox';
import { registerHumanFacedTree } from './human-faced-tree';
import { registerYujuworm } from './yujuworm';
import { registerKikyo } from './kikyo';
import { registerIttanMomen } from './ittan-momen';
import { registerEmbalmer } from './embalmer';
import { registerHellishIbaraki } from './hellish-ibaraki';
import { registerOrochi } from './orochi';
import { registerInariMiketsu } from './inari-miketsu';
import { registerCangfengOneEyed } from './cangfeng-one-eyed';
import { registerRedShadowYoto } from './red-shadow-yoto';
import { registerHaishin } from './haishin';
import { registerKujira } from './kujira';
import { registerOotakemaru } from './ootakemaru';
import { registerKawaArakawa } from './kawa-arakawa';
import { registerCrabSister } from './crab-sister';
import { registerRukia } from './rukia';
import { registerIchigo } from './ichigo';
import { registerTakiyashahime } from './takiyashahime';
import { registerEnshrinedFox } from './enshrined-fox';
import { registerPaperDancer } from './paper-dancer';
import { registerGhostKingShuten } from './ghost-king-shuten';
import { registerStarBear } from './star-bear';
import { registerTenkenOniKiri } from './tenken-oni-kiri';
import { registerGouchang } from './gouchang';
import { registerYiguangong } from './yiguangong';
import { registerFengli } from './fengli';
import { registerBoneBoundPrincess } from './bone-bound-princess';
import { registerKinnara } from './kinnara';
import { registerRRankStrikers } from './r-roster-strikers';
import { registerRRankSupports } from './r-roster-supports';
import { registerScorpionGirl } from './scorpion-girl';
import { registerSuzukaGozen } from './suzuka-gozen';
import { registerDaybreakUbume } from './daybreak-ubume';
import { registerKappaRoster } from './kappa-roster';
import { registerKaruta } from './karuta';
import { registerDreamButterfly } from './dream-butterfly';
import { registerBlazingPeach } from './blazing-peach';
import { registerOniMask } from './oni-mask';
import { registerLumingOotakemaru } from './luming-ootakemaru';
import { registerNightBloom } from './night-bloom';
import { registerFoodSpirit } from './food-spirit';

/** Creates the explicitly migrated content set for modular simulations and coverage checks. */
export function createMigratedContentRegistry(): ContentRegistry {
  const registry = new ContentRegistry();
  registry.registerStatus(passiveSuppressionStatusDefinition);
  registry.registerStatus(soulSuppressionStatusDefinition);
  registerBaselineSouls(registry);
  registerSeaMoonFireJade(registry);
  registerShikagamiCity(registry);
  registerResentmentHannya(registry);
  registerCicadaSnowMaiden(registry);
  registerChihime(registry);
  registerTanjiro(registry);
  registerNezuko(registry);
  registerEmperorOfHeaven(registry);
  registerJi(registry);
  registerTenjukka(registry);
  registerInuyasha(registry);
  registerWhaleSummoner(registry);
  registerOmikane(registry);
  registerWisdomLamp(registry);
  registerWorldLantern(registry);
  registerShiranui(registry);
  registerFirstHaneMountainWind(registry);
  registerGhostServantWhite(registry);
  registerHuaniaoJuan(registry);
  registerHuiyeji(registry);
  registerYanyanluo(registry);
  registerJinyuhime(registry);
  registerHuang(registry);
  registerShinkiHuang(registry);
  registerYijinzhentian(registry);
  registerXiazhongshaonv(registry);
  registerBiganhua(registry);
  registerXiaosongwan(registry);
  registerShuweng(registry);
  registerMountainChild(registry);
  registerInuGod(registry);
  registerPuppetMaster(registry);
  registerShoumu(registry);
  registerLanternBoy(registry);
  registerBeichuifang(registry);
  registerWorldConch(registry);
  registerEvilFloor(registry);
  registerNightSendDog(registry);
  registerNightTearStone(registry);
  registerRainfallStone(registry);
  registerRemembranceFire(registry);
  registerOilChild(registry);
  registerOceanAtlas(registry);
  registerJue(registry);
  registerRedTongue(registry);
  registerFrogPorcelain(registry);
  registerJudge(registry);
  registerPhoenixFire(registry);
  registerVampirePrincess(registry);
  registerDemonFox(registry);
  registerEnma(registry);
  registerYaoqinShi(registry);
  registerDreamEater(registry);
  registerTwoFacedBuddha(registry);
  registerYoungDeer(registry);
  registerKiyohime(registry);
  registerKamaitachi(registry);
  registerUbume(registry);
  registerTwoMouthGirl(registry);
  registerLanternSpirit(registry);
  registerWhiteWolf(registry);
  registerSakuraFairy(registry);
  registerIbarakiDoji(registry);
  registerEbisu(registry);
  registerHannya(registry);
  registerEchoingInsect(registry);
  registerFlyingEdge(registry);
  registerFortuneCat(registry);
  registerYinMoruo(registry);
  registerNirvanaFire(registry);
  registerSoulBird(registry);
  registerWoodCharm(registry);
  registerReturnIncense(registry);
  registerBellSpirit(registry);
  registerSnowSpirit(registry);
  registerDreamPillow(registry);
  registerBatWing(registry);
  registerClothOfProtection(registry);
  registerTreeSpirit(registry);
  registerDamageScalingSouls(registry);
  registerDawnlessDusk(registry);
  registerGravekeeperBeast(registry);
  registerPearl(registry);
  registerSoulDiver(registry);
  registerTulfo(registry);
  registerTubingFire(registry);
  registerRoundabout(registry);
  registerFireCart(registry);
  registerDiekou(registry);
  registerQingnufang(registry);
  registerYuanxingTemple(registry);
  registerDustMound(registry);
  registerRampingSouls(registry);
  registerControlSouls(registry);
  registerReflectiveSouls(registry);
  registerDebuffSouls(registry);
  registerZhen(registry);
  registerRabbitMaru(registry);
  registerPeachBlossom(registry);
  registerSnowGirl(registry);
  registerThreeTailFox(registry);
  registerCarpSpirit(registry);
  registerKappa(registry);
  registerNineLivedCat(registry);
  registerBoySoulSacrifice(registry);
  registerLittleGirl(registry);
  registerEater(registry);
  registerMengPo(registry);
  registerWuguShi(registry);
  registerGreatTengu(registry);
  registerYatagarasu(registry);
  registerShutenDoji(registry);
  registerFoodHairDemon(registry);
  registerSamuraiSpirit(registry);
  registerBoneGirl(registry);
  registerRainWoman(registry);
  registerJumpingBrother(registry);
  registerJumpingYoungerBrother(registry);
  registerJumpingSister(registry);
  registerBingyong(registry);
  registerUglyWoman(registry);
  registerOneEyedMonk(registry);
  registerIronRat(registry);
  registerJiaoTu(registry);
  registerGuanHu(registry);
  registerYamausagi(registry);
  registerFirefly(registry);
  registerButterflySpirit(registry);
  registerTanuki(registry);
  registerSeaMonk(registry);
  registerInsectMaster(registry);
  registerLuminousMoonChaser(registry);
  registerShuraKidomaru(registry);
  registerJinkougyou(registry);
  registerMoonChaser(registry);
  registerSongstress(registry);
  registerTrueFox(registry);
  registerBellEmpress(registry);
  registerSkullGeneral(registry);
  registerCloudMirror(registry);
  registerKidomaru(registry);
  registerHearingSeaGoldfish(registry);
  registerEngagementGod(registry);
  registerArakawa(registry);
  registerYaodaoJi(registry);
  registerLuoxinfufu(registry);
  registerYiMuLian(registry);
  registerQingfangzhu(registry);
  registerGulonghuo(registry);
  registerWannianzhu(registry);
  registerYasha(registry);
  registerHeitongzi(registry);
  registerBaitongzi(registry);
  registerXuetongzi(registry);
  registerBaimugui(registry);
  registerNuraRiku(registry);
  registerMountainWind(registry);
  registerRihefang(registry);
  registerTamamo(registry);
  registerXun(registry);
  registerJuzu(registry);
  registerXiaoxiu(registry);
  registerYi(registry);
  registerMaiyaolang(registry);
  registerCatManager(registry);
  registerGuideng(registry);
  registerAxiang(registry);
  registerPeachMaki(registry);
  registerMenreiki(registry);
  registerOnikiri(registry);
  registerSesshomaru(registry);
  registerYouthfulOotengu(registry);
  registerWhiteFox(registry);
  registerHumanFacedTree(registry);
  registerYujuworm(registry);
  registerKikyo(registry);
  registerIttanMomen(registry);
  registerEmbalmer(registry);
  registerHellishIbaraki(registry);
  registerOrochi(registry);
  registerInariMiketsu(registry);
  registerCangfengOneEyed(registry);
  registerRedShadowYoto(registry);
  registerHaishin(registry);
  registerKujira(registry);
  registerOotakemaru(registry);
  registerKawaArakawa(registry);
  registerCrabSister(registry);
  registerRukia(registry);
  registerIchigo(registry);
  registerTakiyashahime(registry);
  registerEnshrinedFox(registry);
  registerPaperDancer(registry);
  registerGhostKingShuten(registry);
  registerStarBear(registry);
  registerTenkenOniKiri(registry);
  registerGouchang(registry);
  registerYiguangong(registry);
  registerFengli(registry);
  registerBoneBoundPrincess(registry);
  registerKinnara(registry);
  registerRRankStrikers(registry);
  registerRRankSupports(registry);
  registerScorpionGirl(registry);
  registerSuzukaGozen(registry);
  registerDaybreakUbume(registry);
  registerKappaRoster(registry);
  registerKaruta(registry);
  registerDreamButterfly(registry);
  registerBlazingPeach(registry);
  registerOniMask(registry);
  registerLumingOotakemaru(registry);
  registerNightBloom(registry);
  registerFoodSpirit(registry);
  registerRedMaple(registry);
  registerZashiki(registry);
  registerLanternGhost(registry);
  registerSoulReaper(registry);
  registerGenericFallbackHeroes(registry);
  return registry;
}
