"""Refresh the offline optimizer catalog from NetEase's public resources.

No game process, account cookie or emulator connection is used.
"""
from __future__ import annotations

import concurrent.futures
import datetime
import json
import pathlib
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[3]
CONFIG = "https://cbg-yys.res.netease.com/js/game_auto_config.js"
API = "https://g37simulator.webapp.163.com/get_hero_attr"


def read(url: str) -> str:
    request = urllib.request.Request(url, headers={
        "User-Agent": "Mozilla/5.0", "Referer": "https://yys.163.com/shishen/",
    })
    with urllib.request.urlopen(request, timeout=20) as response:
        return response.read().decode("utf-8")


def main() -> None:
    source = read(CONFIG)
    config = json.loads(source[source.index("{"):source.rindex("}") + 1])
    labels = {"攻击加成": "attackAdditionRate", "生命加成": "maxHpAdditionRate",
              "防御加成": "defenseAdditionRate", "暴击": "critRateAdditionVal",
              "暴击伤害": "critPowerAdditionVal", "效果命中": "debuffEnhance",
              "效果抵抗": "debuffResist"}
    boss = set(map(int, config["two_suit_yuhun"]))
    suits = []
    for entry in config["yuhun_list"]:
        sid, name, _, two, four = entry[:5]
        bonus = None
        if sid not in boss:
            for label, key in labels.items():
                if two.startswith(label) and two[len(label):].rstrip("%").replace(".", "", 1).isdigit():
                    bonus = {"name": key, "value": float(two[len(label):].rstrip("%")) / 100}
                    break
        suits.append({"id": sid, "name": name, "bonus": bonus, "four": four, "boss": sid in boss})

    def hero(entry: list) -> dict:
        hid, name, rarity, pinyin = entry[:4]
        result = {"id": hid, "name": name, "rarity": rarity, "pinyin": pinyin, "base": None}
        awake = 0 if rarity in (1, 5, 6) else 1
        for mode in dict.fromkeys((awake, 0)):
            try:
                data = json.loads(read(f"{API}?heroid={hid}&awake={mode}&level=40&star=6"))
                attr = data.get("data")
                if not data.get("success") or not attr or attr.get("maxHp", 0) <= 0:
                    continue
                result["awake"] = bool(mode)
                result["base"] = {"attack": attr["attack"], "hp": attr["maxHp"],
                                  "defense": attr["defense"], "speed": attr["speed"],
                                  "crit": attr["critRate"], "critDamage": 1 + attr["critPower"],
                                  "hit": attr["debuffEnhance"], "resist": attr["debuffResist"]}
                return result
            except (OSError, ValueError, KeyError):
                continue
        return result

    with concurrent.futures.ThreadPoolExecutor(max_workers=8) as pool:
        heroes = list(pool.map(hero, config["hero_list"]))
    catalog = {"updated": datetime.date.today().isoformat(), "sources": [CONFIG, API],
               "heroes": heroes, "suits": suits}
    output = ROOT / "desktop/src/shared/soul-catalog-data.ts"
    output.write_text("// Generated by fetch_soul_catalog.py from public NetEase resources.\n"
                      "export const soulCatalog = " + json.dumps(catalog, ensure_ascii=False, indent=2)
                      + ";\n", encoding="utf-8")
    missing = [h["name"] for h in heroes if h["base"] is None]
    print(json.dumps({"heroes": len(heroes), "suits": len(suits), "missing": missing}, ensure_ascii=False))


if __name__ == "__main__":
    main()
